/**
 * exportPDF.js — PocketWise
 * Generates a monthly PDF report using jsPDF and autoTable.
 */

import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { formatCurrency } from './helpers';

export const exportMonthlyReport = (transactions, user, stats) => {
  const doc = new jsPDF();
  const now = new Date();
  const monthName = now.toLocaleDateString('en-IN', { month: 'long' });
  const year = now.getFullYear();

  // Colors
  const PRIMARY_COLOR = [74, 144, 226]; // #4A90E2

  // 1. Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...PRIMARY_COLOR);
  doc.text(`PocketWise Monthly Report — ${monthName} ${year}`, 14, 22);

  // 2. User Info
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(50, 50, 50);
  const userName = user?.displayName || 'PocketWise Student';
  const collegeName = user?.college || '';
  doc.text(`User: ${userName}`, 14, 32);
  if (collegeName) {
    doc.text(`College: ${collegeName}`, 14, 38);
  }

  // 3. Summary Table
  const startYSummary = collegeName ? 48 : 42;
  doc.autoTable({
    startY: startYSummary,
    head: [['Total Income', 'Total Expense', 'Net Balance']],
    body: [
      [
        formatCurrency(stats.income),
        formatCurrency(stats.expense),
        formatCurrency(stats.balance),
      ],
    ],
    headStyles: { fillColor: PRIMARY_COLOR, textColor: [255, 255, 255], fontStyle: 'bold' },
    theme: 'grid',
    styles: { fontSize: 11, halign: 'center' },
  });

  // 4. Transactions Table
  const txTableStartY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Transaction History', 14, txTableStartY - 5);

  const txData = transactions.map((tx) => [
    new Date(tx.date || tx.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
    tx.category || 'Other',
    tx.name || 'Untitled',
    tx.type === 'income' ? `+${formatCurrency(tx.amount)}` : `-${formatCurrency(tx.amount)}`
  ]);

  doc.autoTable({
    startY: txTableStartY,
    head: [['Date', 'Category', 'Name', 'Amount']],
    body: txData.length > 0 ? txData : [['No transactions recorded yet', '', '', '']],
    headStyles: { fillColor: PRIMARY_COLOR, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [248, 250, 255] }, // Soft blue tint
    styles: { fontSize: 10 },
    columnStyles: {
      3: { halign: 'right', fontStyle: 'bold' } // Amount right aligned
    }
  });

  // 5. Footer (all pages)
  const pageCount = doc.internal.getNumberOfPages();
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(150, 150, 150);
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(
      'Generated by PocketWise — Spend Smart. Save More.',
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  // Save the PDF
  doc.save(`PocketWise_Report_${monthName}_${year}.pdf`);
};
